// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14xCEuo6WebxqzQeXEltFxs5rzvqq4q8',
    appId: '1:412097508290:web:73727cf60968301cdc9c5b',
    messagingSenderId: '412097508290',
    projectId: 'sidi-salem-online-1faa8',
    authDomain: 'sidi-salem-online-1faa8.firebaseapp.com',
    storageBucket: 'sidi-salem-online-1faa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOvDX4azluXPd8KdRb3pF6FE12G-g5TU',
    appId: '1:412097508290:android:95ea0d3a61154a93dc9c5b',
    messagingSenderId: '412097508290',
    projectId: 'sidi-salem-online-1faa8',
    storageBucket: 'sidi-salem-online-1faa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcEOvg_anFzg04Yze26EtcVyCw-pV57M',
    appId: '1:412097508290:ios:cafc1ae2f31ec907dc9c5b',
    messagingSenderId: '412097508290',
    projectId: 'sidi-salem-online-1faa8',
    storageBucket: 'sidi-salem-online-1faa8.appspot.com',
    iosBundleId: 'com.example.sdOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcEOvg_anFzg04Yze26EtcVyCw-pV57M',
    appId: '1:412097508290:ios:dee51b8eeebe2af3dc9c5b',
    messagingSenderId: '412097508290',
    projectId: 'sidi-salem-online-1faa8',
    storageBucket: 'sidi-salem-online-1faa8.appspot.com',
    iosBundleId: 'com.example.sdOnline.RunnerTests',
  );
}
